experiment:
  name: debug
  save_checkpoint_every: 2000
  n_epochs: 20000000

runner:
  cvpr:
    warmup_steps: 100
    n_opt_steps: 1
    increase_roll_every: 5000
    roll_max: 5
    push_eps: 2e-3
    initial_ts: 3.333333333333333e-1
    regular_ts: 3.333333333333333e-2
    use_restpos_for_strain_tensor: True
    opposite_edges: False
    grad_clip: 1.
    optimizer:
      lr: 5e-5
      decay_steps: 50_000
      decay_rate: 5e-1
    material:
      lame_mu_min: 15909
      lame_mu_max: 63636
      lame_lambda_min: 3535.414406069427
      lame_lambda_max: 93333.73508005822
      bending_coeff_min: 6.370782056371576e-08
      bending_coeff_max: 0.0013139737991266374
      density_min: 4.34e-2
      density_max: 7e-1

dataloader:
  num_workers: 8
  batch_size: 1
  pyg_data: True
  dataset:
    cvpr:
      data_root: 'vto_dataset/smpl_parameters'
      split_path: 'datasplits/train.csv'
      smpl_model: 'smpl/SMPL_FEMALE.pkl'
      garment_dict_file: 'garments_dict.pkl'
      obstacle_dict_file: 'smpl_aux.pkl'
      lookup_steps: 5
      pinned_verts: True
      random_betas: True
      betas_scale: 3.
      n_coarse_levels: 3

criterions:
  cvpr.mataug.stretching_energy:
  cvpr.inertia:
  cvpr.gravitational_energy:
    z_axis: 1
  cvpr.collision_penalty:
    weight_start: 5e+3
    weight_max: 5e+5
    eps: 2e-3
    start_rampup_iteration: 50000
    n_rampup_iterations: 100000
  cvpr.mataug.bending_energy:
  cvpr.friction_energy:
    mu: 0.5
    friction_radius: 3e-3

model:
  cvpr:
    collision_radius: 3e-2
    k_world_edges: 1
    use_current_obstacle_pos: True
    n_coarse_levels: 3

device: 'cuda:0'